apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backoffice-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: backoffice
    name: in-cluster
  project: default
  source:
    path: apps/backoffice
    repoURL: https://github.com/rudzm/gitops
    targetRevision: HEAD