apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supply-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: supply
    name: plenti-dev
  project: default
  source:
    path: apps/supply
    repoURL: https://github.com/rudzm/gitops
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true