apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supply-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: supply
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/supply/dev
    repoURL: https://github.com/rudzm/gitops
    targetRevision: HEAD
