apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supply-dev2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - kind: CiliumIdentity
  destination:
    namespace: supply
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/supply/dev2
    repoURL: https://github.com/rudzm/gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true