app-deployment:
  replicaCount: 1

  image:
    repository: nginx
    pullPolicy: Always
    tag: "mainline-alpine-slim"

  imagePullSecrets: []
  fullnameOverride: "supply2"

  podAnnotations: {}

  service:
    type: NodePort
    port: 80

  ingress:
    enabled: true
    className: ""
    annotations: {}

    hosts:
      - host: supply2.plenti.network
        paths:
          - path: /
            pathType: Exact
    tls: []
  
  iap:
    enabled: true
    secretName: supply

  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
